spring:
  application:
    name: restaurant-finder
  main:
    banner-mode: off
  data:
    mongodb:
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
server:
  port: 8080
  servlet:
    context-path: /restaurant-finder
logging:
  level:
    com:
      amazingapps:
        restaurant-finder: ${APP_LOG_LEVEL}
jwt:
  expiration:
    time: ${TOKEN_EXPIRATION_TIME}
  secret:
    key: ${TOKEN_SECRET_KEY}
app:
  version: "@project.version@"