spring:
  application:
    name: restaurant-finder
  main:
    banner-mode: off
  data:
    mongodb:
      uri: localhost:27017/restaurant_finder
server:
  port: 8080
  servlet:
    context-path: /restaurant-finder
logging:
  level:
    com:
      amazingapps:
        restaurant-finder: DEBUG
jwt:
  expiration:
    time: 720000
  secret:
    key: 1234567890
app:
  version: "@project.version@"