spring:
  application:
    name: restaurant-finder
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb+srv://mongo_db_user_123:sR6PDd6As014C5xv@cluster0.2blb24a.mongodb.net/restaurant_finder?retryWrites=true&w=majority
server:
  port: 8080
  servlet:
    context-path: /restaurant-finder
logging:
  level:
    com:
      amazingapps:
        restaurant-finder: DEBUG
jwt:
  expiration:
    time: 720000
  secret:
    key: 1234567890ASDFGHJKLZXCVBNMASD123qwe1!!!!!!
app:
  version: "@project.version@"