spring:
  application:
    name: restaurant-finder
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb://localhost/test
server:
  port: 8080
  servlet:
    context-path: /restaurant-finder
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /
logging:
  level:
    com:
      amazingapps:
        restaurant-finder: DEBUG
jwt:
  expiration:
    time: 720000
  secret:
    key: 1234567890ASDFGHJKLZXCVBNMASD123qwe1!!!!!!
app:
  version: "@project.version@"